- terraform-unity/modules/terraform-eks-cluster/README.md
- terraform-unity/modules/terraform-eks-cluster/main.tf
- Pin the `terraform-unity-eks_module` ref to a specific tag to get rid of terraform validate errors.
- [CHANGE] Ref for `terraform-unity-eks_module`
- N/A
> Use tag for terraform-unity-eks_module ref

- airflow/dags/busybox.py
- airflow/dags/cwl_dag.py
- airflow/dags/docker_cwl_pod.yaml
- airflow/dags/sbg_L1_to_L2_e2e_cwl_dag.py
- airflow/dags/sbg_L1_to_L2_e2e_cwl_step_by_step_dag.py
- airflow/dags/sbg_preprocess_cwl_dag.py
- airflow/docker/cwl/docker_cwl_entrypoint.sh
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
This PR adds functionality that enables executing SBG workflows as independent Airflow Tasks that execute independent CWL documents.
- [ADD] The "busybox" DAG that can be used to test the sharing of data between Tasks that execute a CWL workflow which includes a Docker invocation.
- [ADD] The "sbg-l1-to-l2-e2e-cwl-step-by-step-dag" DAG that executes the SBG end-to-end workflow as separate CWL documents
- [CHANGE] The "docker_cwl.sh" script has been changed to support the additional capability to push the content of a given file to Xcom. This parameter replaces the previous parameter used to change the working directory, which was not really useful.
- [ADD] IAM permission to retrieve SSM parameters from within the KubernetesPodOperator. This will be used to retrieve the venue-dependent …
> 21 decompose sbg e2e cwl workflow

- .gitignore
- lambda/src/airflow-dag-trigger/airflow_dag_trigger.py
- pyproject.toml
- terraform-unity/modules/terraform-unity-sps-airflow/README.md
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- This PR integrates event-based triggering of the SBG DAG in Airflow.
- [ADD] Infrastructure as Code (IaC) for AWS resources involved in event-based triggering of Airflow DAGs. These resources include an inbound staging location (ISL) S3 bucket, an SNS topic for S3 ISL event notifications, an SQS queue subscribed to the SNS topic, and a lambda which is triggered by messages in the SQS queue. 
- #50 
- Manual deployment and testing in `unity-venue-dev` by uploading a file to the ISL bucket and visually verifying through the Airflow UI that the SBG DAG was triggered.
> S3 event-based triggering of SBG DAG

- airflow/dags/busybox.py
- airflow/dags/cwl_dag.py
- airflow/dags/sbg_L1_to_L2_e2e_cwl_step_by_step_dag.py
- airflow/dags/sbg_preprocess_cwl_dag.py
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- This PR is needed to make sure the DAGs that rely on the CWL Pod can still run to completion.
- [FIX] At deployment time, must copy both the .py and the .yaml files to the DAGs folder on the shared PV
- [FIX] Must replace the old PV name "kpo-efs" with the new name "airflow-kpo"
- https://github.com/unity-sds/unity-sps/issues/63
- After the fix, the "busybox" and "sbg-e2e-step-by-step" could run to completion.
> 63 dags pv

- airflow/dags/env_test.py
- airflow/helm/values.tmpl.yaml
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- Make relevant Unity environment variables available in the SPS Airflow deployment
- ADD unity environment variables (project, venue, deployment name, counter, cluster name) to Airflow container environment
- ADD simple environment printing DAG (only for testing, removable)
- unity-sds/unity-sps#85
- Tested with manual cluster
- Used new env_test dag to expose available variables (not visible in Airflow UI)
> Add deployment variables to Airflow environment

- airflow/dags/cwl_dag_new.py
- airflow/dags/karpenter_test.py
- airflow/plugins/unity_sps_utils.py
- utils/airflow_kpo_pv_access.yaml
- utils/trigger_dag.py
- This PR adds an improved version of the CWL DAG which a) does not use the Pod template (which would need to be copied to the DAGS folder separately) and b) uses the Karpenter node pool
- Also added a few additional utilities: a Kubernetes deployment that can be used to mount the shared volume where the tasks write data, and a script to submit N DAGs
- [ADD] New "cwl_dag_new" DAG that can execute a generic DAG on Karpenter node pools
- [ADD] Utilities to monitor the shared volume and to submit N DAGs programmatically
- https://github.com/unity-sds/unity-sps/issues/64
- The CWL DAG was able to execute 10 concurrent DAGs of the "CWL echo" workflow.
- Also able to execute the CWL DAG for the SBG PreProcess step
> Improving the CWL DAG

- utils/post_deployment.sh
- utils/unity_sps_deploy_or_destroy_sps.sh
- Add some utilities script to the code repository
- [ADD] Script unity_sps_deploy_or_destroy_sps.sh is used to deploy/undeploy eks, karpenter, airflow
- [ADD] Script post_deployment.sh is used to register OGC processes after an SPS instance has been deployed
- [Store S3 State on S3](https://github.com/unity-sds/unity-sps/issues/132)
- The deployment/undeplyment script has been tested multiple times successfully
- Also the OGC registration script has been tested successfully after the Dev Nightly venue was deployed
> Add some utilities scripts

- .github/workflows/integration_tests.yml
- unity-test/conftest.py
- unity-test/system/integration/step_defs/test_sbg_preprocess_workflow.py
- utils/post_deployment.sh
- utils/trigger_dag.py
- utils/unity_sps_deploy_or_destroy_sps.sh
- This PR enables the SPS Integration Tests, which currently execute the SBG Preprocess workflow, to execute on the "dev" and "test" venue by passing the proper YAML file.
- [ADD] Support for parametrizing the Integration Tests so they can use different values on different values
- https://github.com/unity-sds/unity-sps/issues/155
- Integration tests using this branch succeed on DEV and TEST venue, in both cases running the full SBG Preprocess workflow
> Parametrize the integration tests

- terraform-unity/modules/terraform-unity-sps-eks/README.md
- terraform-unity/modules/terraform-unity-sps-eks/main.tf
- This PR upgrades the SPS cluster to use version 1.29 of the MCP golden AMIs
- [CHANGE] Cluster version to be "1.29", based on new unity-cs-infra tag "unity-sps-2.1.0"
- https://github.com/unity-sds/unity-sps/issues/159
- Redeployed SPS infrastructure to unity-venue-test using the upgraded branch, deployed was successful and so were the tests
> Upgrading to MCP AMI 1.29

- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- Expose the SPS endpoints for Airflow UI, API, and OGC API.
- Endpoints must be defined as SSM parameters with a specific format.
SSM Parameter names must start with: `/unity/${project}/${venue}/component/`
SSM Parameter endpoint format
```json
{
"componentName": "Airflow UI",
"healthCheckUrl": "https:/....",
"landingPageUrl": "https://..."
}
```
- [ADD] SSM parameters: /unity/unity/dev/component/airflow-ui, /unity/unity/dev/component/airflow-api, /unity/unity/dev/component/ogc-api
- #172 - Expose SPS health check endpoints
Deployed to `unity-venue-dev` and reviewed SSM Parameters. The following parameters were created:
Reviewed the content of each new parameter and confirmed that SSM parameter string can be loaded into correctly formatted JSON:
```bash
{
"componentName": "Airflow UI", …
```
> Define 3 new SSM parameters to store health check endpoints

- terraform-unity/modules/terraform-unity-sps-airflow/README.md
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- Modify existing health check endpoints with new SSM parameter name: `/unity/unity/dev/component/{deployment}`
- Define lifecycle meta-argument to ignore parameter value changes 
- [ADD] SSM parameters: /unity/unity/dev/component/{deployment}/airflow-ui, /unity/unity/dev/component/{deployment}/airflow-api, /unity/unity/dev/component/{deployment}/ogc-api
- #127 - Expose SPS health check endpoints
Deployed to `unity-venue-dev` and reviewed SSM Parameters. The following parameters were created:
- `/unity/unity/dev/component/nikki/airflow-api`
- `/unity/unity/dev/component/nikki/airflow-ui`
- `/unity/unity/dev/component/nikki/ogc-api`
Reviewed the content of each new parameter and confirmed that SSM parameter string can be loaded into correctly formatted JSON:
```bash
{
"componentName": …
```
> 127 health check endpoints

- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- Modify existing health check endpoints with new SSM parameter name: `/unity/unity/dev/component/{deployment}/{counter}`
- [ADD] SSM parameters: /unity/unity/dev/component/{deployment}/airflow-ui, /unity/unity/dev/component/{deployment}/airflow-api, /unity/unity/dev/component/{deployment}/ogc-api
- #127 - Expose SPS health check endpoints
Deployed to `unity-venue-dev` and reviewed SSM Parameters. The following parameters were created:
- `/unity/unity/dev/component/nikki/1/airflow-api`
- `/unity/unity/dev/component/nikki/1/airflow-ui`
- `/unity/unity/dev/component/nikki/1/ogc-api`
Reviewed the content of each new parameter and confirmed that SSM parameter string can be loaded into correctly formatted JSON:
```bash
{
"componentName": "Airflow UI",
"healthCheckUrl": …
```
> Add counter to SSM parameter names for health check endpoints

- unity-test/system/integration/step_defs/test_sbg_preprocess_workflow.py
- Using SSL for the SPS endpoints broke the integration tests, because the test client cannot make a valid HTTP request since the endpoint URL does not match the one in the SSL certificate. This PR instructs the client to ignore certificate validation when making the request.
- [CHANGE] The integration tests will use verify=False when making HTTPS requests (GET or POST)
- https://github.com/unity-sds/unity-sps/issues/128
- Executed the integration test manually on this branch, it succeeded
> Fix the integration tests after enabling SSL

- .github/workflows/smoke_tests.yml
- This PR adds the Ops venue endpoints to those checked by the smoke tests
- [ADD] Ops venue endpoints to smoke tests
- https://github.com/unity-sds/unity-sps/issues/122)
- Verified that smoke tests using the Ops venue endpoints succeed with this branch
> Add Ops venue to smoke tests

- .gitignore
- airflow/dags/busybox.py
- airflow/dags/cwl_dag.py
- airflow/dags/karpenter_test.py
- airflow/dags/sbg_L1_to_L2_e2e_cwl_dag.py
- airflow/dags/sbg_L1_to_L2_e2e_cwl_step_by_step_dag.py
- airflow/dags/sbg_preprocess_cwl_dag.py
- This PR changes the namespace used by the kubernetes-pod-operator from "airflow" to "sps" to be compatible with the latest Terraform changes
- [CHANGE] "kubernetes-pod-operator" namespace from "airflow" to "sps"
- Closed PR: https://github.com/unity-sds/unity-sps/pull/184
- Before the change, DAGs were failing
- After the change, the "cwl_dag", "karpenter_test" and "sbg_preprocess_cwl_dag" are succeding
> Change the DAGs to use "sps" for the pods namespace

- airflow/dags/cwl_dag.py
- airflow/dags/sbg_L1_to_L2_e2e_cwl_step_by_step_dag.py
- airflow/dags/sbg_preprocess_cwl_dag.py
- This PR rectifies the status of a DAG Run to be "failed" if the main worker Task fails, even if the last "cleanup" Task succeeds.
- [CHANGE] Mark the current "setup_task" and "cleanup_task" in several exiting DAGs as the Airflow "setup" and "teardown" Tasks, so that the exit status of the "cleanup_task" is disregarded when setting the final global state of the DAG run.
- https://github.com/unity-sds/unity-sps/issues/189
- Tested using the CWL DAG executing the simple "echo message" workflow. Verified that the status of the DAG run is set depending on the status of the middle "cwl_task" (see picture), independently on the last "cleanup_task" which always succeeds. See picture.
-
> Marking tasks as "setup" and "teardown" in multiple DAGs.

- terraform-unity/modules/terraform-unity-sps-airflow/data.tf
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/data.tf
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/main.tf
- Reverting HTTPS additions to airflow ingresses
- Smoothing over issues with proxying from shared services endpoints 
- CHANGE https references to http
- unity-sds/unity-cs#429
- Deployed and manually added to existing unity-dev instance proxy config for quick testing, available [here](http://unity-dev-httpd-alb-217434782.us-west-2.elb.amazonaws.com:8080/btl/dev1/sps/home)
> Reverting HTTPS endpoints to fix issues with venue services proxy

- terraform-unity/modules/terraform-unity-sps-airflow/data.tf
- terraform-unity/modules/terraform-unity-sps-database/data.tf
- terraform-unity/modules/terraform-unity-sps-karpenter-node-config/data.tf
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/data.tf
- we are changing
/unity/cs/account/network/subnet_list
/unity/cs/account/network/vpc_id
to
/unity/account/network/subnet_list
/unity/account/network/vpc_id
See also:  https://github.com/unity-sds/unity-cs-infra/pull/98
> renaming some ssm params having to do with network

- terraform-unity/modules/terraform-unity-sps-airflow/.terraform.lock.hcl
- terraform-unity/modules/terraform-unity-sps-airflow/README.md
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/README.md
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/main.tf
- Fix the syntax of the Health Check Endpoints for Airflow and OGC to conform to the convention established in: https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/deployment-concepts-and-infrastructure/unity-ssm-parameters/ssm-parameter-naming-requirements-and-conventions
- [CHANGE] Make all health check endpoints start with "unity"
- Have not tested to not perturb the SBG venue, but the change seem trivial.
> Fixing the bug in the health check endpoints

- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/README.md
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/main.tf
- Adding a simple check to verify if the venue proxy lambda is actually available before calling it.
- ADD polling available lambdas before calling proxy lambda
- 
-  Tested on personal airflow deployment. Verified seeing the following in the terraform logs (with none of the previous lambda invocation errors)
```
module.unity-sps-airflow.data.aws_lambda_functions.lambda_check_all: Reading...
...
module.unity-sps-airflow.data.aws_lambda_functions.lambda_check_all: Read complete after 0s [id=us-west-2]
...
module.unity-sps-airflow.aws_lambda_invocation.unity_proxy_lambda_invocation[0]: Creating...
```
> Adding guards around venue proxy lambda call

- airflow/dags/cwl_dag.py
- This PR fixes a bug in the cwl_dag.py which was not working any more when providing the input parameters as a URL
- [FIX] Handling of parameter "cwl_args" in cwl_dag.py
- Verified that with this version I was able to submit and run the cwl_dag.py both with the URL of a YAML file, and with a JSON blob. I also successfully used the latest OGC API to submit the example job request.
> Fixing the cwl_dag.py to accept a URL

- terraform-unity/modules/terraform-unity-sps-airflow/README.md
- terraform-unity/modules/terraform-unity-sps-airflow/data.tf
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/README.md
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/data.tf
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/main.tf
- Fixing issues introduced by #201. Namely, adding a new internal ALB for unity services to connect to without leaving the private subnets.
- ADD Additional security group for internal connections
- ADD Additional k8s-driven ingress for internal-only/private-subnet connections
- CHANGE internal venue-services proxy and healthcheck SSM parameters to reference internal endpoints
- unity-sds/unity-cs#429
- Tested on personal deployment: http://btl-d7-dev-httpd-alb-353487587.us-west-2.elb.amazonaws.com:8080/btl-d7/dev/sps/
- non-venue-proxy endpoint: http://k8s-sps-airflowi-1c931ef118-1938076165.us-west-2.elb.amazonaws.com:5000/
> Fix ALB lockdown configurations

- .pre-commit-config.yaml
- terraform-unity/modules/terraform-unity-sps-airflow/README.md
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- terraform-unity/modules/terraform-unity-sps-initiators/README.md
- terraform-unity/modules/terraform-unity-sps-initiators/main.tf
- Adds s3 bucket policy to block unsecure access on the various S3 buckets created by the unity-sps terraform
- ADD `aws_s3_bucket_policy` entries for the 4 buckets that are created (one in `terraform-unity-sps-airflow`, three in `terraform-unity-sps-initiators`)
- unity-sds/unity-sps#231
- Tested in personal deployment; deployed without issues...
- Unsure of how to test the initiators buckets.
> Adding S3 bucket policies to lock down unsecure access

- airflow/helm/values.tmpl.yaml
- terraform-unity/modules/terraform-unity-sps-airflow/README.md
- terraform-unity/modules/terraform-unity-sps-airflow/main.tf
- terraform-unity/modules/terraform-unity-sps-ogc-processes-api/main.tf
- Fix the airflow page redirects by enabling the [proxyfix airflow parameter](https://airflow.apache.org/docs/apache-airflow/stable/howto/run-behind-proxy.html)
- ADD enable_proxy_fix to airflow helm chart YAML
- unity-sds/unity-cs#429
- Currently deployed in `btl-dd2`/`dev`, accessible at:
- http://btl-dd2-dev-httpd-alb-1592953208.us-west-2.elb.amazonaws.com:8080/btl-dd2/dev/sps/
- https://www.dev.mdps.mcp.nasa.gov:4443/btl-dd2/dev/sps/
> Fix the shared-services/venue-services/airflow proxy request issues

- terraform-unity/modules/terraform-unity-sps-eks/README.md
- terraform-unity/modules/terraform-unity-sps-eks/variables.tf
- terraform-unity/modules/terraform-unity-sps-karpenter/README.md
- terraform-unity/modules/terraform-unity-sps-karpenter/variables.tf
- Adding a sensible default for the "deployment_name" variable for EKS and Karpenter
- [CHANGE] The "deployment_name" variable defaults to ""
- No associated issue, this is a quick fix
- Successfully deployed EKS and Karpenter without having to specify the value of "deployment_name"
> Adding empty "" for deployment name for EKS and Karpenter

- airflow/dags/cwl_dag.py
- ogc-application-packages/cwl_dag.json
- unity-test/system/integration/step_defs/test_cwl_workflows_with_airflow_api.py
- unity-test/system/integration/step_defs/test_cwl_workflows_with_ogc_api.py
- This PR will allow users to select a specific EC2 type when executing a CWL workflow, while removing the ability to generically select memory and CPU. The latter can lead to workflow failures if the user is not careful about their selection.
- [ADD] DAG parameter to select an EC2 type, replacing the parameters to select CPU and memory
- [CHANGE] All integration tests to request an instance type and not a certain amount of memory and CPU
- https://github.com/unity-sds/unity-sps/issues/252
- Integration tests succeeded on personal "luca-1" SPS instance
> [New Feature] Replace selection of CPU, memory with selection of specific EC2 type

- terraform-unity/modules/terraform-unity-sps-eks/.terraform.lock.hcl
- terraform-unity/modules/terraform-unity-sps-eks/versions.tf
- The null provider required a version as an error was encountered in the pre-commit GitHub action.
```bash
TFLint in terraform-unity/modules/terraform-unity-sps-eks/:
1 issue(s) found:
Warning: Missing version constraint for provider "null" in `required_providers` (terraform_required_providers)
on main.tf line 30:
30: resource "null_resource" "eks_post_deployment_actions" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.10.0/docs/rules/terraform_required_providers.md
```
- [ADD] Null provider version and update Terraform lock file.
- N/A work is generated from #250 
- pre-commit now passes with updated versions.tf and lock file: https://github.com/unity-sds/unity-sps/actions/runs/12835312395
> Update EKS module null provider version to resolve pre-commit linting

- terraform-unity/modules/terraform-unity-sps-eks/main.tf
- Bumping the terraform-unity-eks_module (from the unity-cs-infra repo) pinned version up to their fixed version, which has pruned out the references to the ami_1_28 ssm params.
- CHANGE pinned ref in module source
- No relevant issues, chore.
- To be tested in personal deployment, not yet ready for merge.
> Bumping pinned eks_module reference to new (fixed) source tag

- airflow/dags/cwl_dag.py
- airflow/dags/cwl_dag_modular.py
- utils/trigger_dag.py
- This PR resolves a bug which prevented Pods from being allocated to different nodes, causing workflows to fail or under-perform.
- [FIX] Changed the Pod label so that it matches the Pod anti-affinity requirement.
- https://github.com/unity-sds/unity-sps/issues/304
- Applied the fix to both the unity-venue-dev and asips venues, verified that multiple nodes are provisioned when multiple jobs are requested.
> Fixing pod placement over nodes

- terraform-unity/modules/terraform-unity-sps-eks/main.tf
- Updating the tag referenced in the terraform-unity-sps-eks module sourcing
- CHANGE tag from `unity-sps-2.4.1` to `unity-sps-2.4.1-hotfix1`
- No relevant issue
- Tested in local deployment
> Bumping eks_module source tag

- airflow/docker/cwl/Dockerfile
- airflow/docker/cwl/docker_cwl_entrypoint.sh
- airflow/docker/cwl/docker_cwl_entrypoint_modular.sh
Log EC2 instance Id so that users can associate Airflow jobs with underlying physical hardware.
- [ADD] Retrieve instance id from EC2 instance metadata and echo to screen to both CWL DAG and modular CWL DAG
- #357 - [New Feature]: Log the EC2 Instance Id
Ran in `unity-venue-dev` on `unity-nikki-2` deployment.
- Confirmed instance ID is echoed:
```bash
[2025-03-19, 14:57:37 UTC] {pod_manager.py:471} INFO - [base] INSTANCE ID: i-08d4c8bde4561b80f
```
- Confirmed that is the node that the pod launched on; tested for both CWL DAG and modular DAG
> Log instance ID on pod before executing CWL

- terraform-unity/modules/terraform-unity-sps-eks/README.md
- terraform-unity/modules/terraform-unity-sps-eks/main.tf
- terraform-unity/modules/terraform-unity-sps-karpenter/README.md
- terraform-unity/modules/terraform-unity-sps-karpenter/variables.tf
- Update SPS to be deployed on EKS version 1.31
- [CHANGE] Underlying EKS version to be 1.31
- [CHANGE] Upgrade Karpenter Helm chart to be 1.3.3
- [Upgrade SPS to latest EKS version 1.30](https://github.com/unity-sds/unity-sps/issues/243)
- Successfully deployed SPS on EKS 1.31 cluster
- Successfully executed the "echo" DAG and the EMIT CWL DAG
> Updating versions to upgrade to EKS 1.31

- airflow/dags/cwl_dag.py
- airflow/dags/cwl_dag_modular.py
- airflow/plugins/unity_sps_utils.py
- terraform-unity/main.tf
Small updates to CWL DAG and modular CWL DAG to improve usability.
- [CHANGE] Log levels to remove numeric identifier from input parameter display
- [CHANGE] Remove option to use ECR from input parameter display and always log into ECR
- #335 
Ran in `unity-venue-dev` on `unity-nikki-1` deployment.
Confirmed log level display looks correct and log levels still function for entrypoint scripts:
```bash
[2025-04-14, 14:55:40 UTC] {pod_manager.py:471} INFO - [base] 2025-04-14 14:55:40,843 [DEBUG] [mdps_ds_lib.stage_in_out.download_granules_abstract::104] attempting to decode raw_stac_json to JSON object
[2025-04-14, 14:55:40 UTC] {pod_manager.py:471} INFO - [base] 2025-04-14 14:55:40,843 [DEBUG] [mdps_ds_lib.stage_in_out.download_granules_abstract::109] raw_stac_json is not STAC_JSON: …
```
> #335 [New Feature]: Usability improvements to CWL DAGs

- unity-test/system/integration/step_defs/test_cwl_workflows_with_airflow_api.py
- unity-test/system/integration/step_defs/test_cwl_workflows_with_ogc_api.py
- This PR updates all currently supported test cases for the CWL workflow to use the latest version of the Data Services container: 9.11.1
- [CHANGE] Reference the Docker container ghcr.io/unity-sds/unity-data-services:9.11.1
- [CHANGE] Reference CWL workflows in the "unity-sps-workflows" GitHub repository
- [Update tests for CWL (classic) DAG to use the latest version of the Data Services container (9.11.1)](https://github.com/unity-sds/unity-sps/issues/396)
- Executed all tests on SPS instance "luca-1" on unity-venue-dev to success, using both the OGC and Airflow API
> Updating the CWL classic tests to use the latest Data Service Docker container
